// Extracts DEALS and CONTACTS arrays from the original HTML prototype and
// emits SQL seed inserts (supabase/seed/seed.sql). Run: bun run scripts/extract-seed.mjs
import { readFileSync, writeFileSync } from "node:fs";

const html = readFileSync(
  new URL("../../gt-os-jordan-clean (1).html", import.meta.url),
  "utf8",
);

// Pull a "let NAME = [ ... ];" JSON array out of the script by brace matching.
function extractArray(name) {
  const marker = `${name} = [`;
  const start = html.indexOf(marker);
  if (start === -1) throw new Error(`could not find ${name}`);
  let i = start + marker.length - 1; // at '['
  let depth = 0;
  for (let j = i; j < html.length; j++) {
    const ch = html[j];
    if (ch === "[") depth++;
    else if (ch === "]") {
      depth--;
      if (depth === 0) {
        return JSON.parse(html.slice(i, j + 1));
      }
    }
  }
  throw new Error(`unterminated array ${name}`);
}

const sq = (v) =>
  v === null || v === undefined || v === ""
    ? "null"
    : `'${String(v).replace(/'/g, "''")}'`;
const num = (v) => (v === null || v === undefined || v === "" ? "null" : Number(v) || 0);
const bool = (v) => (v ? "true" : "false");

const deals = extractArray("let DEALS");
const contacts = extractArray("let CONTACTS");

let out = `-- AUTO-GENERATED by scripts/extract-seed.mjs from the GT/OS prototype.
-- Seeds reference data only. Owners are stored as initials (rep codes); link to
-- real auth users later via app_user.rep_code.
begin;

`;

// --- deals ---
out += `insert into public.deals
  (legacy_id, company, dealname, contact_name, title, email, phone, stage, value, days_in_stage, owner_code, owner_name, vertical, source, hot, last_activity, n_contacts)
values\n`;
out += deals
  .map(
    (d) =>
      `  (${num(d.id)}, ${sq(d.company)}, ${sq(d.dealname)}, ${sq(d.contact)}, ${sq(
        d.title,
      )}, ${sq(d.email)}, ${sq(d.phone)}, ${sq(d.stage)}, ${num(d.value)}, ${num(
        d.days,
      )}, ${sq(d.owner)}, ${sq(d.ownerName)}, ${sq(d.vertical)}, ${sq(d.source)}, ${bool(
        d.hot,
      )}, ${sq(d.last)}, ${num(d.nContacts)})`,
  )
  .join(",\n");
out += `\non conflict (legacy_id) do nothing;\n\n`;

// --- contacts ---
out += `insert into public.contacts
  (legacy_id, name, title, email, stage, owner_code, dealname)
values\n`;
out += contacts
  .map(
    (c) =>
      `  (${num(c.id)}, ${sq(c.c)}, ${sq(c.t)}, ${sq(c.e)}, ${sq(c.s)}, ${sq(
        c.o,
      )}, ${sq(c.dn)})`,
  )
  .join(",\n");
out += `\non conflict (legacy_id) do nothing;\n\ncommit;\n`;

writeFileSync(new URL("../supabase/seed/seed.sql", import.meta.url), out);
console.log(
  `Wrote seed.sql: ${deals.length} deals, ${contacts.length} contacts`,
);
