// Imports the REAL HubSpot CSV exports into seed SQL that replaces the demo
// data. Run: bun run scripts/import-hubspot.mjs
//   in:  hubspot-crm-exports-all-deals-2026-06-08.csv
//        <unzipped> all-contacts.csv   (pass path as 2nd arg)
//   out: supabase/seed/hubspot-import.sql
//
// Mapping decisions (confirmed with the team):
//   - wipe demo deals/contacts, load real
//   - deal value = Amount when it's a real figure (>1), else 0  (Amounts are
//     mostly missing / 1.0 placeholders in this export)
//   - import all contacts, even without email
import { readFileSync, writeFileSync } from "node:fs";

const dealsPath = process.argv[2] ?? "hubspot-crm-exports-all-deals-2026-06-08.csv";
const contactsPath = process.argv[3];
if (!contactsPath) {
  console.error("usage: bun run scripts/import-hubspot.mjs <deals.csv> <contacts.csv>");
  process.exit(1);
}

// --- RFC4180-ish CSV parser: handles quoted fields, "" escapes, embedded
// commas and newlines. Returns array of objects keyed by header row. ---
function parseCsv(text) {
  const rows = [];
  let row = [];
  let field = "";
  let i = 0;
  let inQuotes = false;
  while (i < text.length) {
    const ch = text[i];
    if (inQuotes) {
      if (ch === '"') {
        if (text[i + 1] === '"') { field += '"'; i += 2; continue; }
        inQuotes = false; i++; continue;
      }
      field += ch; i++; continue;
    }
    if (ch === '"') { inQuotes = true; i++; continue; }
    if (ch === ",") { row.push(field); field = ""; i++; continue; }
    if (ch === "\r") { i++; continue; }
    if (ch === "\n") { row.push(field); rows.push(row); row = []; field = ""; i++; continue; }
    field += ch; i++;
  }
  if (field.length || row.length) { row.push(field); rows.push(row); }
  const header = rows.shift();
  return rows
    .filter((r) => r.length > 1 || (r.length === 1 && r[0] !== ""))
    .map((r) => Object.fromEntries(header.map((h, j) => [h.trim(), (r[j] ?? "").trim()])));
}

// --- value helpers ---
const sq = (v) =>
  v === null || v === undefined || v === ""
    ? "null"
    : `'${String(v).replace(/'/g, "''")}'`;
const bool = (v) => (v ? "true" : "false");

// HubSpot deal stage (with emoji) -> app stage id
const STAGE_MAP = {
  "Closed Lost ❌": "lost",
  "Closed Won 🏆": "won",
  "Opportunity 💡": "attack",
  "MSA/SS ✍️": "close",
  "Proposal Sent 💰": "close",
  "Engagement (RFI/RFP) 💼": "pursue",
};
const mapStage = (s) => STAGE_MAP[s?.trim()] ?? "connection";

// Owner full name (sans "(Deactivated User)") -> app rep_code.
const OWNER_CODE = {
  "Andy Baynes": "AB",
  "Anastasiia Romasiuk": "AR",
  "Daria Konoval": "DK",
  "Ilya Ponomarenko": "IP",
  "John Harris": "JH",
  "Jordan Orloff": "JO",
  "Mariana Kurylo": "MK",
  "Mariia Atrasevych": "MA",
  "Michael Bayler": "MB",
  "Nataliia Eksarova": "NE",
  "Nikita Gorskykh": "NG",
  "Oleksandr Kicha": "OK",
  "Victoria Shvets": "VS",
  "Vlad Solovei": "VO",
};
function cleanOwner(raw) {
  const name = (raw ?? "").replace(/\s*\(Deactivated User\)\s*/i, "").trim();
  if (!name) return { code: null, name: null };
  const code =
    OWNER_CODE[name] ??
    name.split(/\s+/).map((p) => p[0]?.toUpperCase()).slice(0, 2).join("") ??
    null;
  return { code, name };
}

// Deal name often "Company | Contact (notes)" -> split company / contact.
function splitDealName(dealName) {
  const [company, ...rest] = (dealName ?? "").split("|");
  const contact = rest.join("|").replace(/\(.*?\)/g, "").trim();
  return { company: company.trim() || null, contact: contact || null };
}

const num = (v) => {
  const n = Number(String(v).replace(/[^0-9.\-]/g, ""));
  return Number.isFinite(n) ? n : 0;
};
// Amount is a real figure only when > 1 (export is full of 1.0 placeholders).
// The app stores value in THOUSANDS (£k, see src/lib/format.ts), but HubSpot
// Amount is in actual £ — so scale down by 1000 and round.
const dealValue = (amount) => (num(amount) > 1 ? Math.round(num(amount) / 1000) : 0);

// ---------- build SQL ----------
const deals = parseCsv(readFileSync(dealsPath, "utf8"));
const contacts = parseCsv(readFileSync(contactsPath, "utf8"));

let out = `-- AUTO-GENERATED by scripts/import-hubspot.mjs from the 2026-06-08
-- HubSpot exports. Replaces the demo seed with real data.
-- Apply AFTER migration 0006 (legacy_id -> bigint).
begin;

-- wipe demo data (actions cascade from deals)
delete from public.actions;
delete from public.deals;
delete from public.contacts;

`;

// --- deals ---
out += `insert into public.deals
  (legacy_id, company, dealname, contact_name, stage, value, owner_code, owner_name, vertical, source, hot, last_activity)
values\n`;
out += deals
  .map((d) => {
    const { company, contact } = splitDealName(d["Deal Name"]);
    const { code, name } = cleanOwner(d["Deal owner"]);
    return `  (${num(d["Record ID"])}, ${sq(company)}, ${sq(d["Deal Name"])}, ${sq(
      contact,
    )}, ${sq(mapStage(d["Deal Stage"]))}, ${dealValue(d["Amount"])}, ${sq(code)}, ${sq(
      name,
    )}, ${sq(d["Deal Type"] || null)}, null, false, ${sq(d["Last Activity Date"] || null)})`;
  })
  .join(",\n");
out += `\non conflict (legacy_id) do nothing;\n\n`;

// --- contacts ---
out += `insert into public.contacts
  (legacy_id, name, title, email, stage, owner_code, dealname, vertical)
values\n`;
out += contacts
  .map((c) => {
    const fullName = [c["First Name"], c["Last Name"]].filter(Boolean).join(" ").trim();
    const { code } = cleanOwner(c["Contact owner"]);
    return `  (${num(c["Record ID"])}, ${sq(fullName || null)}, ${sq(
      c["Job Title"] || null,
    )}, ${sq(c["Email"] || null)}, ${sq("connection")}, ${sq(code)}, ${sq(
      c["Company Name"] || null,
    )}, ${sq(c["Industry"] || null)})`;
  })
  .join(",\n");
out += `\non conflict (legacy_id) do nothing;\n\ncommit;\n`;

writeFileSync(new URL("../supabase/seed/hubspot-import.sql", import.meta.url), out);

// --- report ---
const byStage = {};
for (const d of deals) byStage[mapStage(d["Deal Stage"])] = (byStage[mapStage(d["Deal Stage"])] ?? 0) + 1;
console.log(`Wrote supabase/seed/hubspot-import.sql`);
console.log(`  deals:    ${deals.length}  by stage: ${JSON.stringify(byStage)}`);
console.log(`  contacts: ${contacts.length}`);
